// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-IHqici6NNy_XCqjoyujU34fGoWZmmP4',
    appId: '1:490560009862:web:e5d3ef39b783e23d0d0307',
    messagingSenderId: '490560009862',
    projectId: 'shop-23e6a',
    authDomain: 'shop-23e6a.firebaseapp.com',
    storageBucket: 'shop-23e6a.firebasestorage.app',
    measurementId: 'G-DPGKE4HTE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJF-XeNm-7xdUAojbeK54_aI386Gwo0Pw',
    appId: '1:490560009862:android:a982523b81fa0ec40d0307',
    messagingSenderId: '490560009862',
    projectId: 'shop-23e6a',
    storageBucket: 'shop-23e6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlsFSsj1Ks9sD91bJPQz0isqEjy8Iu-HU',
    appId: '1:490560009862:ios:dd370f1b9be17af10d0307',
    messagingSenderId: '490560009862',
    projectId: 'shop-23e6a',
    storageBucket: 'shop-23e6a.firebasestorage.app',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlsFSsj1Ks9sD91bJPQz0isqEjy8Iu-HU',
    appId: '1:490560009862:ios:dd370f1b9be17af10d0307',
    messagingSenderId: '490560009862',
    projectId: 'shop-23e6a',
    storageBucket: 'shop-23e6a.firebasestorage.app',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-IHqici6NNy_XCqjoyujU34fGoWZmmP4',
    appId: '1:490560009862:web:465438ba0aead1050d0307',
    messagingSenderId: '490560009862',
    projectId: 'shop-23e6a',
    authDomain: 'shop-23e6a.firebaseapp.com',
    storageBucket: 'shop-23e6a.firebasestorage.app',
    measurementId: 'G-M7JYTC28S0',
  );
}
